import Head from 'next/head';

export const AppHead = () => {
  return (
    <Head>
      <title>Fivicon</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta property="og:title" content="Fivicon - Logo API" />
      <meta property="og:type" content="website" />
      <meta property="og:url" content="https://iili.io/HNAjpzN.jpg" />
      <meta
        property="og:description"
        content="Fivicon free Logo API allows companies to easily update their logos across multiple platforms and channels. logos and icon in png, ico, jpeg and more, try now it is free!"
      />
      <meta property="og:image" content="https://iili.io/HNAjpzN.jpg" />
      <meta property="og:image:width" content="32" />
      <meta property="og:image:height" content="32" />
      <link rel="icon" href="https://iili.io/HNAjpzN.jpg" />
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,100;8..144,200;8..144,300;8..144,400;8..144,500;8..144,600;8..144,700;8..144,800;8..144,900;8..144,1000&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
      />
    </Head>
  );
};
