name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up secrets
        run: |
          echo "DROPLET_USERNAME=${{ secrets.DROPLET_USERNAME }}" >> $GITHUB_ENV
          echo "GITHUB_PAT=${{ secrets.TOKEN_GITHUB }}" >> $GITHUB_ENV

      - name: Deploy to Droplet
        run: |
          git config --global credential.helper 'store --file ~/.git-credentials'
          echo "https://ronen.albagli:${TOKEN_GITHUB}" > ~/.git-credentials
          git pull https://github.com/ronen-albagli/fivicon-next.git
          sshpass -p $DROPLET_PASSWORD ssh -o StrictHostKeyChecking=no $DROPLET_USERNAME@64.226.96.194 'cd /path/to/fivicon-next && git pull && docker-compose up -d'
          rm ~/.git-credentials

