name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up secrets
        run: |
          echo "DROPLET_USERNAME=${{ secrets.DROPLET_USERNAME }}" >> $GITHUB_ENV
          echo "GITHUB_PAT=${{ secrets.GITHUB_PAT }}" >> $GITHUB_ENV

      - name: Deploy to Droplet
        run: |
          git config --global credential.helper 'store --file ~/.git-credentials'
          echo "https://github-username:${GITHUB_PAT}" > ~/.git-credentials
          git pull https://github.com/username/repo.git
          sshpass -p $DROPLET_PASSWORD ssh -o StrictHostKeyChecking=no $DROPLET_USERNAME@64.226.96.194 'cd /path/to/fivicon-next && git pull && docker-compose up -d'
          rm ~/.git-credentials

